using System.IO;
using SnivelerCode.AudioDispatcher.Runtime;
using UnityEditor;
using UnityEngine;

namespace SnivelerCode.AudioDispatcher.Editor
{
    [CustomEditor(typeof(AudioDatabase))]
    public sealed class AudioConfigurationEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            AudioDatabase config = (AudioDatabase) target;

            GUILayout.Space(20);
            GUI.backgroundColor = new Color(0.2f, 0.8f, 0.2f); // Professional Green

            if (GUILayout.Button("Generate C# Constants (AudioIDs)", GUILayout.Height(30)))
            {
                GenerateConstants(config);
            }

            GUI.backgroundColor = Color.white;
        }

        private static void GenerateConstants(AudioDatabase config)
        {
            string dbPath = AssetDatabase.GetAssetPath(config);
            string directory = Path.GetDirectoryName(dbPath);
            string fileName = Path.GetFileNameWithoutExtension(dbPath) + "IDs";

            // Ensure we save next to the config file by default
            string generatedDirectory = directory ?? "Assets";
            string filePath = Path.Combine(generatedDirectory, $"{fileName}.cs");

            var cb = new AudioCodeBuilder();
            cb.Line("//------------------------------------------------------------------------------");
            cb.Line("// <auto-generated>");
            cb.Line("//     This code was generated by Audio Dispatcher Source.");
            cb.Line("//     IDs are generated automatically from your Audio Source project.");
            cb.Line("// </auto-generated>");
            cb.Line("//------------------------------------------------------------------------------");
            cb.Line();

            using (cb.Block($"namespace SnivelerCode.AudioDispatcher"))
            {
                using (cb.Block($"public static class {fileName}"))
                {
                    foreach (AudioDatabase.SoundDefinition sound in config.Sounds)
                    {
                        string safeName = sound.SafeName();
                        int stableHash = Animator.StringToHash(safeName);
                        cb.Line($"public const int {safeName.ToUpper()} = {stableHash};");
                    }
                }
            }

            File.WriteAllText(filePath, cb.ToString());
            AssetDatabase.ImportAsset(filePath, ImportAssetOptions.ForceUpdate);

            Debug.Log($"[AudioDispatcher] Generated IDs at: {filePath}");
        }
    }
}
