using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using AudioConfiguration = SnivelerCode.AudioDispatcher.Runtime.AudioConfiguration;

namespace SnivelerCode.AudioDispatcher.Editor
{
    [CustomEditor(typeof(AudioConfiguration))]
    public sealed class AudioConfigurationEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            AudioConfiguration config = (AudioConfiguration) target;

            GUILayout.Space(20);
            GUI.backgroundColor = new Color(0.2f, 0.8f, 0.2f); // Professional Green

            if (GUILayout.Button("Generate C# Constants (AudioIDs)", GUILayout.Height(30)))
            {
                GenerateConstants(config);
            }

            GUI.backgroundColor = Color.white;
        }

        private void GenerateConstants(AudioConfiguration config)
        {
            string dbPath = AssetDatabase.GetAssetPath(config);
            string directory = Path.GetDirectoryName(dbPath);
            string fileName = Path.GetFileNameWithoutExtension(dbPath) + "IDs";

            // Ensure we save next to the config file by default
            string generatedDirectory = directory ?? "Assets";
            string filePath = Path.Combine(generatedDirectory, $"{fileName}.cs");

            var duplicateNames = new Dictionary<string, int>();
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by SnivelerCode Audio Dispatcher.");
            sb.AppendLine("//     Regenerate this file via the AudioConfiguration inspector.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("namespace SnivelerCode.AudioDispatcher");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {fileName}");
            sb.AppendLine("    {");

            for (int i = 0; i < config.Sounds.Count; i++)
            {
                var sound = config.Sounds[i];
                if (sound.Clip == null) continue;

                // Use the inspector name if set, otherwise clip name
                string rawName = string.IsNullOrEmpty(sound.Name) ? sound.Clip.name : sound.Name;
                string safeName = SanitizeName(rawName);

                if (duplicateNames.TryGetValue(safeName, out int count))
                {
                    count++;
                    duplicateNames[safeName] = count;
                    safeName += $"_{count}";
                }
                else
                {
                    duplicateNames[safeName] = 0;
                }

                sb.AppendLine($"        public const int {safeName.ToUpper()} = {i};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[AudioDispatcher] Generated IDs at: {filePath}");
        }

        private static string SanitizeName(string soundName)
        {
            // Replace non-alphanumeric with underscore, remove leading numbers
            string result = Regex.Replace(soundName, @"[^a-zA-Z0-9_]", "_");
            if (string.IsNullOrEmpty(result)) return "UNKNOWN_SOUND";
            if (char.IsDigit(result[0])) result = "_" + result;
            return result;
        }
    }
}
