//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Audio Dispatcher Source.
//     IDs are generated automatically from your Audio Source project.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnivelerCode.AudioDispatcher
{
    public static class DemoAudioConfigurationIDs
    {
        public const int SHOT = 188032901;
        public const int EXPLOSION = -211360833;
        public const int MOVING = 949806512;
    }

}

