//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SnivelerCode Audio Dispatcher.
//     Regenerate this file via the AudioConfiguration inspector.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnivelerCode.AudioDispatcher
{
    public static class DemoAudioConfigurationIDs
    {
        public const int SHOT = 0;
        public const int EXPLOSION = 1;
    }
}
